/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.NetworkAdmin;

import Business.Enterprise.Enterprise;
import Business.Enterprise.Network;
import Business.IndyPackage.UserAccount;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Albert Carter
 */
public class ViewNetworks extends javax.swing.JPanel {

    Network network;
    Enterprise enterprise;
    JPanel userProcessContainer;

    /** Creates new form AddPerson */
    public ViewNetworks(javax.swing.JPanel jp, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        userProcessContainer = jp;
        
        jLabel1.setText(enterprise.getOrgName() + " " + enterprise.getClass().getSimpleName()+" | CDCs");
        refresh();
    }

    void refresh() {
        int rowcount = managejTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) managejTable.getModel()).removeRow(i);
        }
        
        Network currentNetwork = (Network) enterprise;
        
        ArrayList<Network> clist = currentNetwork.getSystem().getNetworkCatalog().getNetworkList();
        for (Network c : clist) {
            Object[] col = new Object[1];
            col[0] = c;

            ((DefaultTableModel) managejTable.getModel()).addRow(col);
        }
    }
    
    void refreshStaffTable(){
        int rowcount = staffjTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) staffjTable.getModel()).removeRow(i);
        }
        
        ArrayList<UserAccount> userAccount = network.getUserAccountDirectory().getUserAccountList();
        for (UserAccount o : userAccount) {
            Object[] col = new Object[1];
            col[0] = o;

            ((DefaultTableModel) staffjTable.getModel()).addRow(col);
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addnetworkjButton = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        managejTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        refreshjButton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        staffjTable = new javax.swing.JTable();
        removeStaffjButton = new javax.swing.JButton();
        addStaffjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        addnetworkjButton.setText("Add Network");
        addnetworkjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnetworkjButtonActionPerformed(evt);
            }
        });
        add(addnetworkjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 120, -1));

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        managejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Network"
            }
        ));
        managejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managejTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 460, 101));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 211, -1, -1));
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 208, 113, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 187, 460, 10));

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });
        add(refreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });
        add(updatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        staffjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Staff:"
            }
        ));
        jScrollPane2.setViewportView(staffjTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 210, 98));

        removeStaffjButton.setText("Remove Selected Staff");
        removeStaffjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStaffjButtonActionPerformed(evt);
            }
        });
        add(removeStaffjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, 150, -1));

        addStaffjButton.setText("Add Staff");
        addStaffjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffjButtonActionPerformed(evt);
            }
        });
        add(addStaffjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

private void addnetworkjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnetworkjButtonActionPerformed
// TODO add your handling code here:
    AddNetwork awa = new AddNetwork (userProcessContainer, enterprise);
    userProcessContainer.add("Add Provider", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_addnetworkjButtonActionPerformed

private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
// TODO add your handling code here:
    userProcessContainer.remove(this);
    CardLayout c3 = (CardLayout) userProcessContainer.getLayout();
    c3.previous(userProcessContainer);
}//GEN-LAST:event_backjButtonActionPerformed

private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
// TODO add your handling code here:
    refresh();
}//GEN-LAST:event_refreshjButtonActionPerformed

private void managejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managejTableMouseClicked
// TODO add your handling code here:
    //make sure ua is empty, or it will give a null pointer.

    int selectedRow = managejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > managejTable.getRowCount()) {
        return;
    }
    
    network = (Network) managejTable.getValueAt(selectedRow, 0);
                
    namejTextField.setText(network.getOrgName());
    
    refresh();
    refreshStaffTable();



}//GEN-LAST:event_managejTableMouseClicked

private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
// TODO add your handling code here:
    if (network != null) {
               
        network.setOrgName(namejTextField.getText());
        
        refresh();
   
    }
}//GEN-LAST:event_updatejButtonActionPerformed

private void removeStaffjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStaffjButtonActionPerformed
// TODO add your handling code here:
    int selectedRow = staffjTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > staffjTable.getRowCount()) {
        return;
    }

    UserAccount ua = (UserAccount) staffjTable.getValueAt(selectedRow, 0);
    
    network.getStaffDirectory().getStaffList().remove(ua);
    JOptionPane.showMessageDialog(null, "Staff removed from organization.");
}//GEN-LAST:event_removeStaffjButtonActionPerformed

private void addStaffjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffjButtonActionPerformed
// TODO add your handling code here:
    if(network!=null){
    AddNetworkUser awa = new AddNetworkUser (userProcessContainer, enterprise, network);
    userProcessContainer.add("Add Organization", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);}
    else{
        JOptionPane.showMessageDialog(null, "please select an organization to add staff to");
    }
}//GEN-LAST:event_addStaffjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStaffjButton;
    private javax.swing.JButton addnetworkjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable managejTable;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JButton removeStaffjButton;
    private javax.swing.JTable staffjTable;
    private javax.swing.JButton updatejButton;
    // End of variables declaration//GEN-END:variables
}
