/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.NetworkAdmin;

import Business.Enterprise.CDC;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Network;
import Business.IndyPackage.UserAccount;
import Business.Organization.Location;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Albert Carter
 */
public class ViewCDCs extends javax.swing.JPanel {

    CDC cdc;
    Enterprise enterprise;
    JPanel userProcessContainer;

    /** Creates new form AddPerson */
    public ViewCDCs(javax.swing.JPanel jp, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        userProcessContainer = jp;
        
        jLabel1.setText(enterprise.getOrgName() + " " + enterprise.getClass().getSimpleName()+" | CDCs");
        refresh();
    }

    void refresh() {
        int rowcount = managejTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) managejTable.getModel()).removeRow(i);
        }
        
        Network network = (Network) enterprise;
        
        ArrayList<Enterprise> clist = network.getEnterpriseList();
        for (Enterprise c : clist) {
            if(c instanceof CDC){
            Object[] col = new Object[5];
            col[0] = c;
            col[1] = c.getStaffDirectory().getStaffList().size();
            col[2] = c.getLocation().getAddress1();
            col[3] = c.getLocation().getCity();
            col[4] = c.getLocation().getState();

            ((DefaultTableModel) managejTable.getModel()).addRow(col);
        }
        }
    }
    
    void refreshStaffTable(){
        int rowcount = staffjTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) staffjTable.getModel()).removeRow(i);
        }
        
        ArrayList<UserAccount> userAccount = cdc.getUserAccountDirectory().getUserAccountList();
        for (UserAccount o : userAccount) {
            Object[] col = new Object[1];
            col[0] = o;

            ((DefaultTableModel) staffjTable.getModel()).addRow(col);
        }
    }
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        addcdc = new javax.swing.JButton();
        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        managejTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        staffjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        add1jTextField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        refreshjButton = new javax.swing.JButton();
        updatejButton = new javax.swing.JButton();
        add2jLabel = new javax.swing.JLabel();
        add2jTextField = new javax.swing.JTextField();
        add2jLabel1 = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        statejTextField = new javax.swing.JTextField();
        add2jLabel2 = new javax.swing.JLabel();
        zipjTextField = new javax.swing.JTextField();
        add2jLabel3 = new javax.swing.JLabel();
        cou = new javax.swing.JLabel();
        countryjTextField = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        staffjTable = new javax.swing.JTable();
        removeStaffjButton = new javax.swing.JButton();
        addStaffjButton = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        addcdc.setText("Add CDC");
        addcdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcdcActionPerformed(evt);
            }
        });
        add(addcdc, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 158, 120, -1));

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });
        add(backjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, -1));

        managejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CDC", "# Staff", "Address 1", "City", "State"
            }
        ));
        managejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managejTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 46, 375, 101));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 211, -1, -1));
        add(namejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 208, 113, -1));

        jLabel3.setText("# Staff:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 237, -1, -1));

        staffjTextField.setEditable(false);
        add(staffjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 234, 113, -1));

        jLabel4.setText("Address:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 211, -1, -1));
        add(add1jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 208, 113, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 187, 370, 10));

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });
        add(refreshjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 158, -1, -1));

        updatejButton.setText("Update");
        updatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatejButtonActionPerformed(evt);
            }
        });
        add(updatejButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 420, -1, -1));

        add2jLabel.setText("Address:");
        add(add2jLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 237, -1, -1));
        add(add2jTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 234, 113, -1));

        add2jLabel1.setText("City:");
        add(add2jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(219, 263, -1, -1));
        add(cityjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 260, 113, -1));

        statejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statejTextFieldActionPerformed(evt);
            }
        });
        add(statejTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 286, 113, -1));

        add2jLabel2.setText("State:");
        add(add2jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 289, -1, -1));

        zipjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipjTextFieldActionPerformed(evt);
            }
        });
        add(zipjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 312, 113, -1));

        add2jLabel3.setText("Postcode:");
        add(add2jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 315, -1, -1));

        cou.setText("Country:");
        add(cou, new org.netbeans.lib.awtextra.AbsoluteConstraints(199, 341, -1, -1));

        countryjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryjTextFieldActionPerformed(evt);
            }
        });
        add(countryjTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 338, 113, -1));

        staffjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Staff:"
            }
        ));
        jScrollPane2.setViewportView(staffjTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 148, 98));

        removeStaffjButton.setText("Remove Selected Staff");
        removeStaffjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeStaffjButtonActionPerformed(evt);
            }
        });
        add(removeStaffjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, -1));

        addStaffjButton.setText("Add Staff");
        addStaffjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStaffjButtonActionPerformed(evt);
            }
        });
        add(addStaffjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

private void addcdcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcdcActionPerformed
// TODO add your handling code here:
    AddCDC awa = new AddCDC(userProcessContainer, enterprise);
    userProcessContainer.add("Add Provider", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_addcdcActionPerformed

private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
// TODO add your handling code here:
    userProcessContainer.remove(this);
    CardLayout c3 = (CardLayout) userProcessContainer.getLayout();
    c3.previous(userProcessContainer);
}//GEN-LAST:event_backjButtonActionPerformed

private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
// TODO add your handling code here:
    refresh();
}//GEN-LAST:event_refreshjButtonActionPerformed

private void managejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managejTableMouseClicked
// TODO add your handling code here:
    //make sure ua is empty, or it will give a null pointer.

    int selectedRow = managejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > managejTable.getRowCount()) {
        return;
    }
    
    cdc = (CDC) managejTable.getValueAt(selectedRow, 0);
            
    namejTextField.setText(cdc.getOrgName());
    staffjTextField.setText(Integer.toString(cdc.getStaffDirectory().getStaffList().size()));
    add1jTextField.setText(cdc.getLocation().getAddress1());
    add2jTextField.setText(cdc.getLocation().getAddress2());
    cityjTextField.setText(cdc.getLocation().getCity());
    statejTextField.setText(cdc.getLocation().getState());
    zipjTextField.setText(cdc.getLocation().getPostal());
    countryjTextField.setText(cdc.getLocation().getCountry());

    refresh();
    refreshStaffTable();



}//GEN-LAST:event_managejTableMouseClicked

private void updatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatejButtonActionPerformed
// TODO add your handling code here:
    if (cdc != null) {
       
        Location l = cdc.getLocation();
        
        cdc.setOrgName(namejTextField.getText());
        l.setAddress1(add1jTextField.getText());
        l.setAddress2(add2jTextField.getText());
        l.setCity(cityjTextField.getText());
        l.setState(statejTextField.getText());
        l.setPostal(zipjTextField.getText());
        l.setCountry(countryjTextField.getText());
        
        refresh();
   
    }
}//GEN-LAST:event_updatejButtonActionPerformed

private void statejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statejTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_statejTextFieldActionPerformed

private void zipjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipjTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_zipjTextFieldActionPerformed

private void countryjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryjTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_countryjTextFieldActionPerformed

private void removeStaffjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeStaffjButtonActionPerformed
// TODO add your handling code here:
    int selectedRow = staffjTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > staffjTable.getRowCount()) {
        return;
    }

    UserAccount ua = (UserAccount) staffjTable.getValueAt(selectedRow, 0);
    
    cdc.getStaffDirectory().getStaffList().remove(ua);
    JOptionPane.showMessageDialog(null, "Staff removed from organization.");
}//GEN-LAST:event_removeStaffjButtonActionPerformed

private void addStaffjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStaffjButtonActionPerformed
// TODO add your handling code here:
    if(cdc!=null){
    AddCDCUser awa = new AddCDCUser (userProcessContainer, enterprise, cdc);
    userProcessContainer.add("Add Organization", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);}
    else{
        JOptionPane.showMessageDialog(null, "please select an organization to add staff to");
    }
}//GEN-LAST:event_addStaffjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add1jTextField;
    private javax.swing.JLabel add2jLabel;
    private javax.swing.JLabel add2jLabel1;
    private javax.swing.JLabel add2jLabel2;
    private javax.swing.JLabel add2jLabel3;
    private javax.swing.JTextField add2jTextField;
    private javax.swing.JButton addStaffjButton;
    private javax.swing.JButton addcdc;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JLabel cou;
    private javax.swing.JTextField countryjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable managejTable;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JButton removeStaffjButton;
    private javax.swing.JTable staffjTable;
    private javax.swing.JTextField staffjTextField;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JButton updatejButton;
    private javax.swing.JTextField zipjTextField;
    // End of variables declaration//GEN-END:variables
}
