/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.CDC;

import Business.Enterprise.CDC;
import Business.Enterprise.Enterprise;
import Business.IndyPackage.Disease;
import Business.IndyPackage.UserAccount;
import Business.IndyPackage.Vaccine;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Albert Carter
 */
public class AddCDCVaccine extends javax.swing.JPanel {
    Disease D;
    UserAccount ua;
    Enterprise e;
    JPanel userProcessContainer;
    /** Creates new form AddPerson */
    public AddCDCVaccine(javax.swing.JPanel jp, Enterprise e, UserAccount ua) {
        initComponents();
        this.e = e;
        userProcessContainer = jp;
        this.ua=ua;
        
        jLabel1.setText(e.getOrgName() + " " + e.getClass().getSimpleName()+ " | Add Vaccines to Catalog");
        refresh();
    }
    
    void refresh() {
        int rowcount = managejTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) managejTable.getModel()).removeRow(i);
        }
        CDC cdc = (CDC) e;
        ArrayList<Disease> clist = cdc.getSystem().getDiseaseCatalog().getDiseaseList();
        for (Disease c : clist) {
            Object[] col = new Object[3];
            col[0] = c;

            ((DefaultTableModel) managejTable.getModel()).addRow(col);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        addVaccinejButton = new javax.swing.JButton();
        namejTextField = new javax.swing.JTextField();
        titlejLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        managejTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        titlejLabel1 = new javax.swing.JLabel();
        titlejLabel2 = new javax.swing.JLabel();
        titlejLabel3 = new javax.swing.JLabel();
        titlejLabel4 = new javax.swing.JLabel();
        cdcjSpinner = new javax.swing.JSpinner();
        phdjSpinner = new javax.swing.JSpinner();
        lifespanjSpinner = new javax.swing.JSpinner();
        providerjSpinner = new javax.swing.JSpinner();
        titlejLabel5 = new javax.swing.JLabel();
        priceSpinner = new javax.swing.JSpinner();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        addVaccinejButton.setText("Add Vaccine");
        addVaccinejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addVaccinejButtonActionPerformed(evt);
            }
        });

        titlejLabel.setText("Vaccine Name:");

        managejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Disease"
            }
        ));
        managejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managejTable);

        jLabel4.setText("Select a Disease for the Vaccine:");

        titlejLabel1.setText("Lifespan (in days):");

        titlejLabel2.setText("CDC %  Paid:");

        titlejLabel3.setText("PHD %  Paid:");

        titlejLabel4.setText("Provider %  Paid:");

        cdcjSpinner.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(100L), Long.valueOf(1L)));

        phdjSpinner.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(100L), Long.valueOf(1L)));

        lifespanjSpinner.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(1), Integer.valueOf(0), null, Integer.valueOf(1)));

        providerjSpinner.setModel(new javax.swing.SpinnerNumberModel(Long.valueOf(0L), Long.valueOf(0L), Long.valueOf(100L), Long.valueOf(1L)));

        titlejLabel5.setText("Price:");

        priceSpinner.setModel(new javax.swing.SpinnerNumberModel(Double.valueOf(1.0d), Double.valueOf(0.0d), null, Double.valueOf(0.25d)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 302, Short.MAX_VALUE)
                        .addComponent(addVaccinejButton))
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titlejLabel5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(titlejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(titlejLabel, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(priceSpinner)
                            .addComponent(lifespanjSpinner, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(namejTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(titlejLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titlejLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(titlejLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(providerjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(phdjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cdcjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(titlejLabel)
                    .addComponent(titlejLabel2)
                    .addComponent(cdcjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titlejLabel1)
                    .addComponent(titlejLabel3)
                    .addComponent(phdjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lifespanjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titlejLabel4)
                            .addComponent(providerjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlejLabel5)
                            .addComponent(priceSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(addVaccinejButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
// TODO add your handling code here:
    userProcessContainer.remove(this);
    CardLayout c3 = (CardLayout)userProcessContainer.getLayout();
    c3.previous(userProcessContainer);
}//GEN-LAST:event_backjButtonActionPerformed

private void addVaccinejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addVaccinejButtonActionPerformed
// TODO add your handling code here:
    Long phdPercent = (Long) phdjSpinner.getValue();
    Long cdcPercent = (Long) cdcjSpinner.getValue();
    Long providerPercent = (Long) providerjSpinner.getValue();
    double price = (Double) priceSpinner.getValue();
    Integer lifespan = (Integer) lifespanjSpinner.getValue();
     
    if((phdPercent + cdcPercent + providerPercent)!=100){
        JOptionPane.showMessageDialog(null, "Make sure invoicing equals 100%");
    }
    
    if(D!=null){
    CDC cdc = (CDC) e;
    String name = namejTextField.getText();
   
    
    Vaccine vaccine = cdc.getSystem().getVaccineCatalog().newVaccine();
    
    vaccine.setName(name);
    vaccine.setDisease(D);
    vaccine.setPhdPercent(phdPercent);
    vaccine.setCdcPercent(cdcPercent);
    vaccine.setProviderPercent(providerPercent);
    vaccine.setLifespan(lifespan);
    vaccine.setPrice(price);
    
    refresh();
    JOptionPane.showMessageDialog(null, "Vaccine Added to List");
    }else{
        JOptionPane.showMessageDialog(null, "Please select an associated disease");
        return;
    }
}//GEN-LAST:event_addVaccinejButtonActionPerformed

private void managejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managejTableMouseClicked
// TODO add your handling code here:
    int selectedRow = managejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > managejTable.getRowCount()) {
        return;
    }

    D = (Disease) managejTable.getValueAt(selectedRow, 0);
}//GEN-LAST:event_managejTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addVaccinejButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JSpinner cdcjSpinner;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner lifespanjSpinner;
    private javax.swing.JTable managejTable;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JSpinner phdjSpinner;
    private javax.swing.JSpinner priceSpinner;
    private javax.swing.JSpinner providerjSpinner;
    private javax.swing.JLabel titlejLabel;
    private javax.swing.JLabel titlejLabel1;
    private javax.swing.JLabel titlejLabel2;
    private javax.swing.JLabel titlejLabel3;
    private javax.swing.JLabel titlejLabel4;
    private javax.swing.JLabel titlejLabel5;
    // End of variables declaration//GEN-END:variables
}
