/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClinicAdmin.java
 *
 * Created on Nov 15, 2011, 5:49:23 PM
 */
package UserInterface.CDC;

import Business.Enterprise.Enterprise;
import Business.IndyPackage.UserAccount;
import UserInterface.UserInterface;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Albert Carter
 */
public class ManageCDC extends UserInterface {

    UserAccount ua;
    Enterprise enterprise;
    JPanel userProcessContainer;

    /** Creates new form ClinicAdmin */
    public ManageCDC(javax.swing.JPanel jp, Enterprise enterprise, UserAccount ua) {
        super();
        initComponents();
        this.enterprise = enterprise;
        userProcessContainer = jp;
        this.ua=ua;

        jLabel1.setText(enterprise.getOrgName() + " " + enterprise.getClass().getSimpleName()+ " | Management Work Area");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        vaccineRequestjButton = new javax.swing.JButton();
        manufacturjButton = new javax.swing.JButton();
        diseasejButton = new javax.swing.JButton();
        vaccinejButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        vaccineRequestjButton.setText("Manage Vaccine Requests");
        vaccineRequestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccineRequestjButtonActionPerformed(evt);
            }
        });

        manufacturjButton.setText("Request Manufacture of Vaccines");
        manufacturjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manufacturjButtonActionPerformed(evt);
            }
        });

        diseasejButton.setText("Manage Diseases");
        diseasejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diseasejButtonActionPerformed(evt);
            }
        });

        vaccinejButton.setText("Manage Vaccines");
        vaccinejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccinejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(423, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(diseasejButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(manufacturjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(vaccineRequestjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vaccinejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addGap(251, 251, 251))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(vaccineRequestjButton)
                .addGap(18, 18, 18)
                .addComponent(manufacturjButton)
                .addGap(18, 18, 18)
                .addComponent(diseasejButton)
                .addGap(18, 18, 18)
                .addComponent(vaccinejButton)
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void vaccineRequestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccineRequestjButtonActionPerformed
// TODO add your handling code here:
    ViewCDCRequests awa = new ViewCDCRequests(userProcessContainer, enterprise, ua);
    userProcessContainer.add("Manage Vaccine Requests to the CDC", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_vaccineRequestjButtonActionPerformed

private void manufacturjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manufacturjButtonActionPerformed
// TODO add your handling code here:
    RequestCDCManufacture awa = new RequestCDCManufacture(userProcessContainer, enterprise, ua);
    userProcessContainer.add("Request More Vaccines to be manufactured", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
    
}//GEN-LAST:event_manufacturjButtonActionPerformed

private void diseasejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diseasejButtonActionPerformed
// TODO add your handling code here:
    ManageCDCDiseases awa = new ManageCDCDiseases(userProcessContainer, enterprise, ua);
    userProcessContainer.add("Manage Existing Diseases", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_diseasejButtonActionPerformed

private void vaccinejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccinejButtonActionPerformed
// TODO add your handling code here:
    ManageCDCVaccines awa = new ManageCDCVaccines(userProcessContainer, enterprise, ua);
    userProcessContainer.add("Manage CDC Vaccines", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_vaccinejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton diseasejButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manufacturjButton;
    private javax.swing.JButton vaccineRequestjButton;
    private javax.swing.JButton vaccinejButton;
    // End of variables declaration//GEN-END:variables
}
