/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.Admin;

import Business.Enterprise.PHD;
import Business.Organization.Location;
import Business.Providers.Clinic;
import Business.Providers.Hospital;
import Business.Providers.Pharmacy;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Albert Carter
 */
public class AddProvider extends javax.swing.JPanel {
    PHD phd;
    JPanel userProcessContainer;
    /** Creates new form AddPerson */
    public AddProvider(javax.swing.JPanel jp, PHD phd) {
        initComponents();
        this.phd = phd;
        userProcessContainer = jp;
        
        jLabel1.setText(phd.getOrgName() + " " + phd.getClass().getSimpleName()+ " | Add Provider");
        typejComboBox.removeAllItems();
        typejComboBox.addItem("Hospital");
        typejComboBox.addItem("Clinic");
        typejComboBox.addItem("Distributor");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        addjButton = new javax.swing.JButton();
        add2jTextField = new javax.swing.JTextField();
        countryjTextField = new javax.swing.JTextField();
        add2jLabel = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        add2jLabel1 = new javax.swing.JLabel();
        add2jLabel2 = new javax.swing.JLabel();
        statejTextField = new javax.swing.JTextField();
        add2jLabel3 = new javax.swing.JLabel();
        zipjTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        add1jTextField = new javax.swing.JTextField();
        cou = new javax.swing.JLabel();
        namejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        typejComboBox = new javax.swing.JComboBox();
        cou1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        addjButton.setText("Add Provider");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        countryjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryjTextFieldActionPerformed(evt);
            }
        });

        add2jLabel.setText("Address:");

        add2jLabel1.setText("City:");

        add2jLabel2.setText("State:");

        statejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statejTextFieldActionPerformed(evt);
            }
        });

        add2jLabel3.setText("Postcode:");

        zipjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipjTextFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Address:");

        cou.setText("Country:");

        jLabel2.setText("Name:");

        typejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cou1.setText("Type:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(add2jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(add2jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cou1)
                                        .addComponent(cou)
                                        .addComponent(add2jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(countryjTextField)
                                        .addComponent(zipjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                        .addComponent(typejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(add2jLabel)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addGap(9, 9, 9)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(add2jTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                                        .addComponent(add1jTextField))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namejTextField)))
                .addContainerGap(225, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addjButton)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add2jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add2jLabel)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add1jTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add2jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add2jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zipjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add2jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cou))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cou1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(addjButton))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
// TODO add your handling code here:
    userProcessContainer.remove(this);
    CardLayout c3 = (CardLayout)userProcessContainer.getLayout();
    c3.previous(userProcessContainer);
}//GEN-LAST:event_backjButtonActionPerformed

private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
// TODO add your handling code here:
     String type = (String) typejComboBox.getSelectedItem();
          
     if(type.equals("Hospital")){
         Hospital c = phd.newHospital();
         Location l = new Location(); 
         c.setLocation(l);
        
        c.setOrgName(namejTextField.getText());
        l.setAddress1(add1jTextField.getText());
        l.setAddress2(add2jTextField.getText());
        l.setCity(cityjTextField.getText());
        l.setState(statejTextField.getText());
        l.setPostal(zipjTextField.getText());
        l.setCountry(countryjTextField.getText());
        
        JOptionPane.showMessageDialog(null, "Hospital Added");
     }
     
     if(type.equals("Clinic")){
         Clinic c = phd.newClinic();
         Location l = c.getLocation();
        
        c.setOrgName(namejTextField.getText());
        l.setAddress1(add1jTextField.getText());
        l.setAddress2(add2jTextField.getText());
        l.setCity(cityjTextField.getText());
        l.setState(statejTextField.getText());
        l.setPostal(zipjTextField.getText());
        l.setCountry(countryjTextField.getText());
        
        JOptionPane.showMessageDialog(null, "Clinic Added");
     } 
     
     if(type.equals("Pharmacy")){
         Pharmacy c = phd.newPharmacy();
         Location l = c.getLocation();
        
        c.setOrgName(namejTextField.getText());
        l.setAddress1(add1jTextField.getText());
        l.setAddress2(add2jTextField.getText());
        l.setCity(cityjTextField.getText());
        l.setState(statejTextField.getText());
        l.setPostal(zipjTextField.getText());
        l.setCountry(countryjTextField.getText());
        
        JOptionPane.showMessageDialog(null, "Pharmacy Added");
     }
        
}//GEN-LAST:event_addjButtonActionPerformed

private void countryjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryjTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_countryjTextFieldActionPerformed

private void statejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statejTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_statejTextFieldActionPerformed

private void zipjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipjTextFieldActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_zipjTextFieldActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add1jTextField;
    private javax.swing.JLabel add2jLabel;
    private javax.swing.JLabel add2jLabel1;
    private javax.swing.JLabel add2jLabel2;
    private javax.swing.JLabel add2jLabel3;
    private javax.swing.JTextField add2jTextField;
    private javax.swing.JButton addjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JLabel cou;
    private javax.swing.JLabel cou1;
    private javax.swing.JTextField countryjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JTextField statejTextField;
    private javax.swing.JComboBox typejComboBox;
    private javax.swing.JTextField zipjTextField;
    // End of variables declaration//GEN-END:variables
}
