/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.Admin;

import Business.Enterprise.Distributor;
import Business.Enterprise.Enterprise;
import Business.IndyPackage.Person;
import Business.IndyPackage.UserAccount;
import Business.Roles.AdminRole;
import Business.Roles.Manager;
import Business.Roles.PayableRole;
import Business.Roles.ReceivableRole;
import Business.Roles.TreasuryRole;
import Business.Roles.WarehouseRole;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Albert Carter
 */
public class AddUser extends javax.swing.JPanel {

    Enterprise enterprise;
    JPanel userProcessContainer;

    /** Creates new form AddPerson */
    public AddUser(javax.swing.JPanel jp, Enterprise enterprise) {
        initComponents();
        this.enterprise = enterprise;
        userProcessContainer = jp;

        jLabel1.setText(enterprise.getOrgName() + " " + enterprise.getClass().getSimpleName() + " | Add User");

        RolejComboBox.removeAllItems();
        RolejComboBox.addItem("Admin");
        RolejComboBox.addItem("Manager");
        RolejComboBox.addItem("Payable");
        RolejComboBox.addItem("Receivable");
        RolejComboBox.addItem("Treasury");
                
        

        statusjComboBox.removeAllItems();
        statusjComboBox.addItem("Active");
        statusjComboBox.addItem("Disabled");
        
        //here, i'm making sure it's not one of these other roles.
        extraRoles();

        personjComboBox.removeAllItems();
        for (Person p : enterprise.getPersonDirectory().getPersonList()) {
            personjComboBox.addItem(p);
        }
    }
    
    public void extraRoles(){
        if(enterprise instanceof Distributor){
            RolejComboBox.addItem("Warehouse Manager");
            return;
        }
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        usernamejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordjTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        addUserAccountjButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        RolejComboBox = new javax.swing.JComboBox();
        statusjComboBox = new javax.swing.JComboBox();
        personjComboBox = new javax.swing.JComboBox();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        jLabel2.setText("username:");

        jLabel3.setText("password:");

        jLabel4.setText("Role:");

        jLabel6.setText("Status:");

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        addUserAccountjButton.setText("Add User");
        addUserAccountjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserAccountjButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Person:");

        RolejComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        statusjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        personjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addComponent(jLabel2))
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernamejTextField)
                            .addComponent(passwordjTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(RolejComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(statusjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(personjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(backjButton)
                                .addGap(18, 18, 18)
                                .addComponent(addUserAccountjButton)))))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usernamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(RolejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(statusjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(personjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backjButton)
                    .addComponent(addUserAccountjButton))
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
// TODO add your handling code here:
    userProcessContainer.remove(this);
    CardLayout c3 = (CardLayout) userProcessContainer.getLayout();
    c3.previous(userProcessContainer);
}//GEN-LAST:event_backjButtonActionPerformed

private void addUserAccountjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserAccountjButtonActionPerformed
// TODO add your handling code here:
    UserAccount tempUA = enterprise.getUserAccountDirectory().newUserAccount();
//    enterprise.addBusinessUserAccount(tempUA); Can't get this to work. This whole global UA idea was a bad one anyway...

    String username = usernamejTextField.getText();
    String password = passwordjTextField.getText();
    String srole = (String) RolejComboBox.getSelectedItem();
    String status = (String) statusjComboBox.getSelectedItem();
    Person person = (Person) personjComboBox.getSelectedItem();

    tempUA.setUserName(username);
    tempUA.setPassword(password);
    tempUA.setPerson(person);
    tempUA.setStatus(status);
    tempUA.setEnterprise(enterprise);
    
    if(srole.equalsIgnoreCase("Admin")){
        tempUA.setRole(new AdminRole());
    }
    
    if(srole.equals("Manager")){
        tempUA.setRole(new Manager());
    }
    
    if(srole.equals("Payable")){
        tempUA.setRole(new PayableRole());
    }
        
    if(srole.equals("Receivable")){
        tempUA.setRole(new ReceivableRole());
    }
        
    if(srole.equals("Warehouse Manager")){
        tempUA.setRole(new WarehouseRole());
    }
    
    if(srole.equals("Treasury")){
        tempUA.setRole(new TreasuryRole());
    }
    
    System.out.println(enterprise.getUserAccountDirectory().getUserAccountList());

    JOptionPane.showMessageDialog(null, "User Account Added");

}//GEN-LAST:event_addUserAccountjButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox RolejComboBox;
    private javax.swing.JButton addUserAccountjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField passwordjTextField;
    private javax.swing.JComboBox personjComboBox;
    private javax.swing.JComboBox statusjComboBox;
    private javax.swing.JTextField usernamejTextField;
    // End of variables declaration//GEN-END:variables
}
