/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClinicAdmin.java
 *
 * Created on Nov 15, 2011, 5:49:23 PM
 */
package UserInterface.Admin;

import Business.Enterprise.Enterprise;
import UserInterface.UserInterface;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Albert Carter
 */
public class ManufacturerAdmin extends UserInterface {

    Enterprise enterprise;
    JPanel userProcessContainer;

    /** Creates new form ClinicAdmin */
    public ManufacturerAdmin(javax.swing.JPanel jp, Enterprise enterprise) {
        super();
        initComponents();
        this.enterprise = enterprise;
        userProcessContainer = jp;

        jLabel1.setText(enterprise.getOrgName() + " " + enterprise.getClass().getSimpleName()+ " | Admin Work Area");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        personjButton = new javax.swing.JButton();
        userjButton = new javax.swing.JButton();
        orgjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        personjButton.setText("Manage People");
        personjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personjButtonActionPerformed(evt);
            }
        });

        userjButton.setText("Manage Users");
        userjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userjButtonActionPerformed(evt);
            }
        });

        orgjButton.setText("Manage Organizations");
        orgjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orgjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(340, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(personjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(userjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(orgjButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(251, 251, 251))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(personjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(orgjButton)
                .addContainerGap(151, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void personjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personjButtonActionPerformed
// TODO add your handling code here:
    ViewPeople awa = new ViewPeople(userProcessContainer, enterprise);
    userProcessContainer.add("AdminWorkAreaJPanel", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_personjButtonActionPerformed

private void userjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userjButtonActionPerformed
// TODO add your handling code here:
    ViewUsers awa = new ViewUsers(userProcessContainer, enterprise);
    userProcessContainer.add("UserWorkArea", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_userjButtonActionPerformed

private void orgjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orgjButtonActionPerformed
// TODO add your handling code here:
    ViewOrgs awa = new ViewOrgs(userProcessContainer, enterprise);
    userProcessContainer.add("View Organizations", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_orgjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton orgjButton;
    private javax.swing.JButton personjButton;
    private javax.swing.JButton userjButton;
    // End of variables declaration//GEN-END:variables
}
