/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClinicAdmin.java
 *
 * Created on Nov 15, 2011, 5:49:23 PM
 */
package UserInterface.Manager;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PHD;
import Business.IndyPackage.UserAccount;
import UserInterface.UserInterface;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Albert Carter
 */
public class ManagePHD extends UserInterface {

    UserAccount ua;
    Enterprise enterprise;
    JPanel userProcessContainer;

    /** Creates new form ClinicAdmin */
    public ManagePHD(javax.swing.JPanel jp, Enterprise enterprise, UserAccount ua) {
        super();
        initComponents();
        this.enterprise = enterprise;
        userProcessContainer = jp;
        this.ua=ua;

        jLabel1.setText(enterprise.getOrgName() + " " + enterprise.getClass().getSimpleName()+ " | Management Work Area");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        inventoryjButton = new javax.swing.JButton();
        requestjButton = new javax.swing.JButton();
        intelligencejButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        inventoryjButton.setText("View Provider Inventory");
        inventoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryjButtonActionPerformed(evt);
            }
        });

        requestjButton.setText("Manage Vaccine Requests");
        requestjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestjButtonActionPerformed(evt);
            }
        });

        intelligencejButton.setText("Business Intelligence");
        intelligencejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                intelligencejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(423, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(requestjButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(inventoryjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(intelligencejButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addGap(251, 251, 251))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(inventoryjButton)
                .addGap(18, 18, 18)
                .addComponent(requestjButton)
                .addGap(18, 18, 18)
                .addComponent(intelligencejButton)
                .addContainerGap(116, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void requestjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestjButtonActionPerformed
// TODO add your handling code here:
    ViewPHDRequests awa = new ViewPHDRequests(userProcessContainer, enterprise, ua);
    userProcessContainer.add("Manage PHD View Requests", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_requestjButtonActionPerformed

private void inventoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryjButtonActionPerformed
// TODO add your handling code here:
    SeePHDInventory awa = new SeePHDInventory(userProcessContainer, enterprise, ua);
    userProcessContainer.add("Manage PHD See Inventory", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_inventoryjButtonActionPerformed

private void intelligencejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_intelligencejButtonActionPerformed
// TODO add your handling code here:
    PHD phd = (PHD) enterprise;
    PHDIntelligence awa = new PHDIntelligence(userProcessContainer, phd, ua);
    userProcessContainer.add("Provider Business Ingelligence", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_intelligencejButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton intelligencejButton;
    private javax.swing.JButton inventoryjButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton requestjButton;
    // End of variables declaration//GEN-END:variables
}
