/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.Manager;

import Business.IndyPackage.UserAccount;
import Business.IndyPackage.Vaccine;
import Business.IndyPackage.WorkRequest;
import Business.Providers.Inventory;
import Business.Providers.Provider;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Albert Carter
 */
public class SeeProviderInventory extends javax.swing.JPanel {

    UserAccount ua;
    Provider p;
    JPanel userProcessContainer;
    WorkRequest WR;

    /** Creates new form AddPerson */
    public SeeProviderInventory(javax.swing.JPanel jp, Provider p, UserAccount ua) {
        initComponents();
        this.p = p;
        userProcessContainer = jp;
        this.ua=ua;

        jLabel1.setText(p.getOrgName() + " " + p.getClass().getSimpleName()+" | Manage Inventory");
        refresh();
    }

    void refresh() {
        int rowcount = managejTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) managejTable.getModel()).removeRow(i);
        }
        Map map = (Map) p.getWorkRequestList(); //cast the HashMap to map
        Set set = map.entrySet(); //and get the entry set
        Iterator iter = set.iterator(); //get the number of entries
        
        while(iter.hasNext()){
        Map.Entry entry = (Map.Entry) iter.next();
        ArrayList<WorkRequest> entryRequests = (ArrayList<WorkRequest>) entry.getValue();
        for(WorkRequest c : entryRequests){
            if(c.getInvoice()!=null){
                Vaccine vaccine = c.getInventory().getVaccine();
            Object[] col = new Object[6];
            col[0] = vaccine.getName();
            col[1] = c.getInventory().getCount();
            col[2] = c.getInventory().getSerialNo();
            col[3] = vaccine.getLifespan();
            col[4] = vaccine.getDisease().getName();
            col[5] = c;

            ((DefaultTableModel) managejTable.getModel()).addRow(col);
            }
    }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        managejTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        refreshjButton = new javax.swing.JButton();
        vaccinejLabel = new javax.swing.JLabel();
        diseasejLabel = new javax.swing.JLabel();
        remainingjLabel = new javax.swing.JLabel();
        serialjLabel = new javax.swing.JLabel();
        manufacturerjLabel = new javax.swing.JLabel();
        dateMadejLabel = new javax.swing.JLabel();
        expirationjLabel = new javax.swing.JLabel();
        warehousejLabel = new javax.swing.JLabel();
        vaccinejLabel1 = new javax.swing.JLabel();
        diseasejLabel1 = new javax.swing.JLabel();
        remainingjLabel1 = new javax.swing.JLabel();
        serialjLabel1 = new javax.swing.JLabel();
        manufacturerjLabel1 = new javax.swing.JLabel();
        dateMadejLabel1 = new javax.swing.JLabel();
        expirationjLabel1 = new javax.swing.JLabel();
        warehousejLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        managejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vaccine Name", "Count", "Serial No", "Lifespan", "Disease", "WR Title"
            }
        ));
        managejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managejTable);

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        vaccinejLabel.setText("Vaccine Name:");

        diseasejLabel.setText("Associate Disease:");

        remainingjLabel.setText("Amount Remaining:");

        serialjLabel.setText("Serial No:");

        manufacturerjLabel.setText("Manufacturer:");

        dateMadejLabel.setText("Manufacture Date:");

        expirationjLabel.setText("Expiration Date:");

        warehousejLabel.setText("Storage Warehouse:");

        vaccinejLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        vaccinejLabel1.setText(" ");

        diseasejLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        diseasejLabel1.setText(" ");

        remainingjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        remainingjLabel1.setText(" ");

        serialjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        serialjLabel1.setText(" ");

        manufacturerjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        manufacturerjLabel1.setText(" ");

        dateMadejLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        dateMadejLabel1.setText(" ");

        expirationjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        expirationjLabel1.setText(" ");

        warehousejLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        warehousejLabel2.setText(" ");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(refreshjButton)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(diseasejLabel)
                                    .addComponent(remainingjLabel)
                                    .addComponent(vaccinejLabel)
                                    .addComponent(serialjLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serialjLabel1)
                                    .addComponent(remainingjLabel1)
                                    .addComponent(vaccinejLabel1)
                                    .addComponent(diseasejLabel1))
                                .addGap(116, 116, 116)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warehousejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(expirationjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(22, 22, 22)
                                            .addComponent(manufacturerjLabel))
                                        .addComponent(dateMadejLabel)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warehousejLabel2)
                                    .addComponent(expirationjLabel1)
                                    .addComponent(dateMadejLabel1)
                                    .addComponent(manufacturerjLabel1))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backjButton)
                .addContainerGap(406, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(refreshjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vaccinejLabel)
                            .addComponent(vaccinejLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diseasejLabel)
                            .addComponent(diseasejLabel1))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remainingjLabel)
                            .addComponent(remainingjLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serialjLabel)
                            .addComponent(serialjLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(backjButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(manufacturerjLabel)
                            .addComponent(manufacturerjLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateMadejLabel1)
                            .addComponent(dateMadejLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(expirationjLabel)
                            .addComponent(expirationjLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(warehousejLabel2)
                            .addComponent(warehousejLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(140, 140, 140))
        );
    }// </editor-fold>//GEN-END:initComponents

private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
// TODO add your handling code here:
    userProcessContainer.remove(this);
    CardLayout c3 = (CardLayout) userProcessContainer.getLayout();
    c3.previous(userProcessContainer);
}//GEN-LAST:event_backjButtonActionPerformed

private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
// TODO add your handling code here:
    refresh();
}//GEN-LAST:event_refreshjButtonActionPerformed

private void managejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managejTableMouseClicked
// TODO add your handling code here:
    int selectedRow = managejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > managejTable.getRowCount()) {
        return;
    }

    WR = (WorkRequest) managejTable.getValueAt(selectedRow, 5);
    Inventory inventory = WR.getInventory();
    Vaccine vaccine = inventory.getVaccine();
    
    vaccinejLabel1.setText(vaccine.getName());
    diseasejLabel1.setText(vaccine.getDisease().getName());
    remainingjLabel1.setText(Integer.toString(inventory.getCount()-inventory.getNumberAdministered()));
    serialjLabel1.setText(Integer.toString(inventory.getSerialNo()));
    
    manufacturerjLabel1.setText(inventory.getManufacturer().getOrgName());
    dateMadejLabel1.setText(DateFormat.getInstance().format(inventory.getDateCreated()));
    expirationjLabel1.setText(DateFormat.getInstance().format(inventory.getDateExpired()));
    warehousejLabel2.setText(inventory.getWarehouse().getOrgName());
    
    
}//GEN-LAST:event_managejTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backjButton;
    private javax.swing.JLabel dateMadejLabel;
    private javax.swing.JLabel dateMadejLabel1;
    private javax.swing.JLabel diseasejLabel;
    private javax.swing.JLabel diseasejLabel1;
    private javax.swing.JLabel expirationjLabel;
    private javax.swing.JLabel expirationjLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable managejTable;
    private javax.swing.JLabel manufacturerjLabel;
    private javax.swing.JLabel manufacturerjLabel1;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JLabel remainingjLabel;
    private javax.swing.JLabel remainingjLabel1;
    private javax.swing.JLabel serialjLabel;
    private javax.swing.JLabel serialjLabel1;
    private javax.swing.JLabel vaccinejLabel;
    private javax.swing.JLabel vaccinejLabel1;
    private javax.swing.JLabel warehousejLabel;
    private javax.swing.JLabel warehousejLabel2;
    // End of variables declaration//GEN-END:variables
}
