/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ClinicAdmin.java
 *
 * Created on Nov 15, 2011, 5:49:23 PM
 */
package UserInterface.Distributor;

import UserInterface.Distributor.ShipDistributorRequests;
import Business.Enterprise.Enterprise;
import Business.IndyPackage.UserAccount;
import UserInterface.UserInterface;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Albert Carter
 */
public class ManageDistributor extends UserInterface {

    UserAccount ua;
    Enterprise enterprise;
    JPanel userProcessContainer;

    /** Creates new form ClinicAdmin */
    public ManageDistributor(javax.swing.JPanel jp, Enterprise enterprise, UserAccount ua) {
        super();
        initComponents();
        this.enterprise = enterprise;
        userProcessContainer = jp;
        this.ua=ua;

        jLabel1.setText(enterprise.getOrgName() + " " + enterprise.getClass().getSimpleName()+ " | Management Work Area");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        manageVaccinesjButton = new javax.swing.JButton();
        manageInventoryjButton = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        manageVaccinesjButton.setText("Manage Vaccine Requests");
        manageVaccinesjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageVaccinesjButtonActionPerformed(evt);
            }
        });

        manageInventoryjButton.setText("Manage Inventory");
        manageInventoryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageInventoryjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(423, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageVaccinesjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addGap(251, 251, 251))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageInventoryjButton, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                        .addGap(251, 251, 251))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(manageVaccinesjButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(manageInventoryjButton)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void manageVaccinesjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageVaccinesjButtonActionPerformed
// TODO add your handling code here:
    ManageDistributorRequests awa = new ManageDistributorRequests(userProcessContainer, enterprise, ua);
    userProcessContainer.add("Manage Distributor See Requests", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_manageVaccinesjButtonActionPerformed

private void manageInventoryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageInventoryjButtonActionPerformed
// TODO add your handling code here:
    SeeDistributorInventory awa = new SeeDistributorInventory(userProcessContainer, enterprise, ua);
    userProcessContainer.add("See Distributor Inventory", awa);
    CardLayout c1 = (CardLayout) userProcessContainer.getLayout();
    c1.next(userProcessContainer);
}//GEN-LAST:event_manageInventoryjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageInventoryjButton;
    private javax.swing.JButton manageVaccinesjButton;
    // End of variables declaration//GEN-END:variables
}
