/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.Distributor;

import Business.Enterprise.Distributor;
import Business.Enterprise.Enterprise;
import Business.IndyPackage.UserAccount;
import Business.IndyPackage.VaccinePackage;
import Business.Organization.Organization;
import Business.Organization.Warehouse;
import Business.Providers.Inventory;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Albert Carter
 */
public class ManageWarehouses extends javax.swing.JPanel {

    UserAccount ua;
    Enterprise e;
    JPanel userProcessContainer;
    Inventory inventory;
    Warehouse w;

    /** Creates new form AddPerson */
    public ManageWarehouses(javax.swing.JPanel jp, Enterprise e, UserAccount ua, Inventory p) {
        initComponents();
        this.e = e;
        userProcessContainer = jp;
        this.ua = ua;
        this.inventory = p;

        jLabel1.setText(e.getOrgName() + " " + e.getClass().getSimpleName() + " | Assign Packages to Warehouses");

        vNamejTextField.setText(p.getVaccine().getName());
        dNamejTextField.setText(p.getVaccine().getDisease().getName());

        try {
            warehousejTextField.setText(p.getWarehouse().getOrgName()); //in case the warehouse hasn't been decided yet.
        } catch (Exception ex) {
            warehousejTextField.setText("-unassigned-");
        }

        dosesjTextField.setText(Integer.toString(p.getCount()));

        refresh();
    }

    void refresh() {
        int rowcount = warehousejTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) warehousejTable.getModel()).removeRow(i);
        }

        Distributor d = (Distributor) e;
        
        //need to make sure there's a warehouse here.
        
        ArrayList<Organization> clist = d.getOrganizationList();
        for (Organization o : clist) {
            
            if(o instanceof Warehouse){
            w = (Warehouse) o; //cast each organization to type Warehouse

            Object[] col = new Object[5];
            col[0] = w;
            col[1] = w.getLocation().getAddress1();
            col[2] = w.getLocation().getCity();
            col[3] = w.getLocation().getState();
            col[4] = w.getLocation().getCountry();

            ((DefaultTableModel) warehousejTable.getModel()).addRow(col);
        }
        }
    }
    
    void refreshWarehouseInventory(){
            int selectedRow = warehousejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > warehousejTable.getRowCount()) {
        return;
    }
    
    w = (Warehouse) warehousejTable.getValueAt(selectedRow, 0); //get the selected warehouse
    
    int rowcount = inventoryjTable.getRowCount();
    int i;
    for (i = rowcount - 1; i >= 0; i--) {
        ((DefaultTableModel) inventoryjTable.getModel()).removeRow(i);
    }

    Distributor d = (Distributor) e;

    ArrayList<Inventory> clist = d.getInventoryList();
    for (Inventory in : clist) {
        if(in.getWarehouse()==w){
            Object[] col = new Object[3];
            col[0] = in;
            col[1] = in.getManufacturer();
            col[2] = in.getCount();

            ((DefaultTableModel) inventoryjTable.getModel()).addRow(col);
        }
    }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        backjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        warehousejTable = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryjTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        refreshjButton = new javax.swing.JButton();
        assignjButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        vNamejTextField = new javax.swing.JTextField();
        warehousejTextField = new javax.swing.JTextField();
        dNamejTextField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dosesjTextField = new javax.swing.JTextField();
        quantityjSpinner = new javax.swing.JSpinner();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        backjButton.setText("<<Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        warehousejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Warehouse", "Address 1", "City", "State", "Country"
            }
        ));
        warehousejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                warehousejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(warehousejTable);

        inventoryjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Vaccines", "Manufacturer", "Number in Stock"
            }
        ));
        jScrollPane2.setViewportView(inventoryjTable);

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        assignjButton.setText("Assign Vaccines to Warehouse");
        assignjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignjButtonActionPerformed(evt);
            }
        });

        jLabel2.setText("Vaccine Name:");

        jLabel3.setText("Select a Warehouse:");

        jLabel4.setText("Selected Warehouse's Inventory:");

        jLabel5.setText("Current Warehouse:");

        vNamejTextField.setEditable(false);

        warehousejTextField.setEditable(false);

        dNamejTextField.setEditable(false);

        jLabel6.setText("Associate Disease:");

        jLabel7.setText("Number of Doses:");

        dosesjTextField.setEditable(false);

        quantityjSpinner.setModel(new javax.swing.SpinnerNumberModel(5, 5, 50000, 5));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(382, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dNamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(warehousejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(dosesjTextField))
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(refreshjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                        .addComponent(quantityjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(assignjButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                    .addComponent(backjButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(vNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(warehousejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dosesjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshjButton)
                    .addComponent(assignjButton)
                    .addComponent(quantityjSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addComponent(backjButton)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
// TODO add your handling code here:
    userProcessContainer.remove(this);
    CardLayout c3 = (CardLayout) userProcessContainer.getLayout();
    c3.previous(userProcessContainer);
}//GEN-LAST:event_backjButtonActionPerformed

private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
// TODO add your handling code here:
    refresh();
}//GEN-LAST:event_refreshjButtonActionPerformed

private void assignjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignjButtonActionPerformed
// TODO add your handling code here:
    //get the warehouse value
    int selectedRow = warehousejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > warehousejTable.getRowCount()) {
        return;
    }

//    Warehouse w = (Warehouse) warehousejTable.getValueAt(selectedRow, 0); //we need to get the warehouse to transfer to, too.
    //don't need this, because warehouse is now global
    
    int quantity = (Integer) quantityjSpinner.getValue();
    Distributor distributor = (Distributor) e;
    
    //if new quantity is too large
    if(quantity > inventory.getCount()){
        JOptionPane.showMessageDialog(null, "Please select a number of doses less than or equal to the doses available");
        return;
    }
    
    //if quantity is equal
    if(quantity == inventory.getCount()){
        inventory.setWarehouse(w);
        warehousejTextField.setText(w.getOrgName());
        refreshWarehouseInventory();
        refresh();
        return;
    }
    
    //if quantity is smaller
    if(quantity<inventory.getCount()){
        inventory.setCount(inventory.getCount() - quantity); //first, reset the old inventory count
        
        Inventory newi = distributor.newInventory(); //make a new inventory
        newi.setCount(quantity);
        newi.setDateCreated(inventory.getDateCreated()); //and copy everything about the old one into it.
        newi.setManufacturer(inventory.getManufacturer());
        newi.setPrice(inventory.getPrice());
        newi.setDateExpired(inventory.getDateExpired());
        newi.setVaccine(inventory.getVaccine());
        newi.setSerialNo(inventory.getSerialNo());
        newi.setWarehouse(w);
        
        dosesjTextField.setText(Integer.toString(inventory.getCount()));
        warehousejTextField.setText(newi.getWarehouse().getOrgName());
        refresh();
        refreshWarehouseInventory();
        return;
    }
    
   

}//GEN-LAST:event_assignjButtonActionPerformed

private void warehousejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_warehousejTableMouseClicked
// TODO add your handling code here:
    refreshWarehouseInventory();


}//GEN-LAST:event_warehousejTableMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton assignjButton;
    private javax.swing.JButton backjButton;
    private javax.swing.JTextField dNamejTextField;
    private javax.swing.JTextField dosesjTextField;
    private javax.swing.JTable inventoryjTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSpinner quantityjSpinner;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JTextField vNamejTextField;
    private javax.swing.JTable warehousejTable;
    private javax.swing.JTextField warehousejTextField;
    // End of variables declaration//GEN-END:variables
}
