/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddPerson.java
 *
 * Created on Nov 15, 2011, 6:42:05 PM
 */
package UserInterface.Payable;

import Business.Enterprise.CDC;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PHD;
import Business.IndyPackage.Invoice;
import Business.IndyPackage.UserAccount;
import Business.IndyPackage.Vaccine;
import Business.IndyPackage.WorkRequest;
import Business.Providers.Inventory;
import Business.Providers.Provider;
import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Albert Carter
 */
public class SeeAccountsPayable extends javax.swing.JPanel {

    UserAccount ua;
    Enterprise e;
    JPanel userProcessContainer;
    WorkRequest WR;

    /** Creates new form AddPerson */
    public SeeAccountsPayable(javax.swing.JPanel jp, Enterprise e, UserAccount ua) {
        initComponents();
        this.e = e;
        userProcessContainer = jp;
        this.ua = ua;

        jLabel1.setText(e.getOrgName() + " " + e.getClass().getSimpleName() + " | Accounts Payable");
        refresh();
    }

    void refresh() {
        int rowcount = managejTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) managejTable.getModel()).removeRow(i);
        }

        Map map = (Map) e.getWorkRequestList(); //cast the HashMap to map
        Set set = map.entrySet(); //and get the entry set

        Iterator iter = set.iterator(); //get the number of entries

        while (iter.hasNext()) {
            Map.Entry entry = (Map.Entry) iter.next();
            ArrayList<WorkRequest> entryRequests = (ArrayList<WorkRequest>) entry.getValue();
            for (WorkRequest c : entryRequests) {
                if (c.getInvoice() != null && c.getInvoice().getPayment().equals("unpaid") && c.getInvoice().getStatus().equals("payable")) {
                    Object[] col = new Object[7];

                    Vaccine vaccine = c.getInventory().getVaccine();
                    double vaccinePricePer = vaccine.getPrice();
                    int count = c.getInventory().getCount();

                    col[0] = vaccine;
                    col[1] = count;
                    col[2] = vaccinePricePer;
                    col[3] = count * vaccinePricePer;
                    col[4] = c.getInvoice().getOwedTo();
                    col[5] = c.getEditorEnterprise().getOrgName();
                    col[6] = c;

                    ((DefaultTableModel) managejTable.getModel()).addRow(col);
                }
            }
        }
    }

    void refreshInventory() {
        int rowcount = inventoryjTable.getRowCount();
        int i;
        for (i = rowcount - 1; i >= 0; i--) {
            ((DefaultTableModel) inventoryjTable.getModel()).removeRow(i);
        }
        Map map = (Map) e.getWorkRequestList(); //cast the HashMap to map
        Set set = map.entrySet(); //and get the entry set

        Iterator iter = set.iterator(); //get the number of entries

        while (iter.hasNext()) {
            Map.Entry entry = (Map.Entry) iter.next();
            ArrayList<WorkRequest> entryRequests = (ArrayList<WorkRequest>) entry.getValue();

            for (WorkRequest c : entryRequests) {
                if (c.getCount() == WR.getCount() && c.getInvoice()==null) {
                    Object[] col = new Object[6];
                    Inventory inventory = c.getInventory();
                    Vaccine vaccine = inventory.getVaccine();
                    
                    col[0] = vaccine.getName();
                    col[1] = inventory.getCount();
                    col[2] = inventory.getSerialNo();
                    col[3] = vaccine.getLifespan();
                    col[4] = vaccine.getDisease();
                    col[5] = c.getOriginator();


                    ((DefaultTableModel) inventoryjTable.getModel()).addRow(col);
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        managejTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        refreshjButton = new javax.swing.JButton();
        vaccinejLabel = new javax.swing.JLabel();
        diseasejLabel = new javax.swing.JLabel();
        orderedjLabel = new javax.swing.JLabel();
        pricejLabel = new javax.swing.JLabel();
        manufacturerjLabel = new javax.swing.JLabel();
        dateMadejLabel = new javax.swing.JLabel();
        expirationjLabel = new javax.swing.JLabel();
        warehousejLabel = new javax.swing.JLabel();
        vaccinejLabel1 = new javax.swing.JLabel();
        diseasejLabel1 = new javax.swing.JLabel();
        orderedjLabel1 = new javax.swing.JLabel();
        priceLabel1 = new javax.swing.JLabel();
        manufacturerjLabel1 = new javax.swing.JLabel();
        dateMadejLabel1 = new javax.swing.JLabel();
        expirationjLabel1 = new javax.swing.JLabel();
        warehousejLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        payableTojLabel = new javax.swing.JLabel();
        totalOwedjLabel = new javax.swing.JLabel();
        invoiceDateLabel = new javax.swing.JLabel();
        invoiceByjLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        invoiceDateLabel1 = new javax.swing.JLabel();
        totalOwedjLabel1 = new javax.swing.JLabel();
        payableTojLabel1 = new javax.swing.JLabel();
        invoiceByjLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryjTable = new javax.swing.JTable();
        percentjLabel = new javax.swing.JLabel();
        percentjLabel1 = new javax.swing.JLabel();
        treasuryjButton = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        paymentOwedjLabel = new javax.swing.JLabel();
        paymentOwedjLabel1 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("jLabel1");

        managejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Vaccine Ordered", "Number", "Price (ea)", "Total Price", "Payable to", "Invoiced By", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        managejTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managejTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(managejTable);
        managejTable.getColumnModel().getColumn(6).setResizable(false);
        managejTable.getColumnModel().getColumn(6).setPreferredWidth(1);

        refreshjButton.setText("Refresh");
        refreshjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshjButtonActionPerformed(evt);
            }
        });

        vaccinejLabel.setText("Vaccine Name:");

        diseasejLabel.setText("Associate Disease:");

        orderedjLabel.setText("Number Ordered:");

        pricejLabel.setText("Price for Each:");

        manufacturerjLabel.setText("Manufacturer:");

        dateMadejLabel.setText("Manufacture Date:");

        expirationjLabel.setText("Expiration Date:");

        warehousejLabel.setText("Storage Warehouse:");

        vaccinejLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        vaccinejLabel1.setText(" ");

        diseasejLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        diseasejLabel1.setText(" ");

        orderedjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        orderedjLabel1.setText(" ");

        priceLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        priceLabel1.setText(" ");

        manufacturerjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        manufacturerjLabel1.setText(" ");

        dateMadejLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        dateMadejLabel1.setText(" ");

        expirationjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        expirationjLabel1.setText(" ");

        warehousejLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        warehousejLabel2.setText(" ");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        payableTojLabel.setText("Payable to:");

        totalOwedjLabel.setText("Total Owed:");

        invoiceDateLabel.setText("Date Invoice Created:");

        invoiceByjLabel.setText("Invoiced By:");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        invoiceDateLabel1.setText(" ");

        totalOwedjLabel1.setText(" ");

        payableTojLabel1.setText("  ");

        invoiceByjLabel1.setText(" ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Provider Current Inventory:");

        inventoryjTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Vaccine Name", "Count", "Serial No", "Lifespan", "Disease", "Provider"
            }
        ));
        inventoryjTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryjTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(inventoryjTable);

        percentjLabel.setText("Percent Paid:");

        percentjLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        percentjLabel1.setText(" ");

        treasuryjButton.setText("Sent to Treasury");
        treasuryjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treasuryjButtonActionPerformed(evt);
            }
        });

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        paymentOwedjLabel.setText("Payment Status:");

        paymentOwedjLabel1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diseasejLabel)
                    .addComponent(orderedjLabel)
                    .addComponent(vaccinejLabel)
                    .addComponent(pricejLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceLabel1)
                    .addComponent(orderedjLabel1)
                    .addComponent(vaccinejLabel1)
                    .addComponent(diseasejLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warehousejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(expirationjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(manufacturerjLabel))
                        .addComponent(dateMadejLabel)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warehousejLabel2)
                    .addComponent(expirationjLabel1)
                    .addComponent(dateMadejLabel1)
                    .addComponent(manufacturerjLabel1))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(percentjLabel)
                                .addComponent(invoiceByjLabel))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(invoiceByjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(14, 14, 14)
                                    .addComponent(percentjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(56, 56, 56)
                            .addComponent(payableTojLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(payableTojLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceDateLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceDateLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentOwedjLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(totalOwedjLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalOwedjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paymentOwedjLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                        .addContainerGap())))
            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(refreshjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 594, Short.MAX_VALUE)
                        .addComponent(treasuryjButton))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 778, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshjButton)
                    .addComponent(treasuryjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(vaccinejLabel)
                                    .addComponent(vaccinejLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(diseasejLabel)
                                    .addComponent(diseasejLabel1))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(orderedjLabel)
                                    .addComponent(orderedjLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(pricejLabel)
                                    .addComponent(priceLabel1)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(invoiceDateLabel)
                                        .addComponent(invoiceDateLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(payableTojLabel)
                                        .addComponent(payableTojLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(invoiceByjLabel1)
                                        .addComponent(invoiceByjLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(percentjLabel1)
                                        .addComponent(percentjLabel)))))
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manufacturerjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateMadejLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expirationjLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(warehousejLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(manufacturerjLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dateMadejLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(expirationjLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(warehousejLabel2))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(99, 99, 99)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(paymentOwedjLabel)
                                .addComponent(paymentOwedjLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(totalOwedjLabel)
                                .addComponent(totalOwedjLabel1)))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(294, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

private void refreshjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshjButtonActionPerformed
// TODO add your handling code here:
    refresh();
}//GEN-LAST:event_refreshjButtonActionPerformed

private void managejTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managejTableMouseClicked
// TODO add your handling code here:
    int selectedRow = managejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > managejTable.getRowCount()) {
        return;
    }

    WR = (WorkRequest) managejTable.getValueAt(selectedRow, 6);

    Inventory inventory = WR.getInventory();
    Vaccine vaccine = inventory.getVaccine();
    Invoice invoice = WR.getInvoice();

    //there is a bug here because i can't display the wr name.

    vaccinejLabel1.setText(vaccine.getName());
    diseasejLabel1.setText(vaccine.getDisease().getName());
    orderedjLabel1.setText(Integer.toString(invoice.getCount()));
    priceLabel1.setText(Double.toString(vaccine.getPrice()));

    //this panel is built for PHDs, CDCs, and Providers, so I have to show the correct one.
    if (e instanceof Provider) {
        percentjLabel1.setText(Double.toString(vaccine.getProviderPercent()) + "%");
    }

    if (e instanceof PHD) {
        percentjLabel1.setText(Double.toString(vaccine.getPhdPercent()) + "%");
    }

    if (e instanceof CDC) {
        percentjLabel1.setText(Double.toString(vaccine.getCdcPercent()) + "%");
    }

    manufacturerjLabel1.setText(inventory.getManufacturer().getOrgName());
    dateMadejLabel1.setText(DateFormat.getInstance().format(inventory.getDateCreated()));
    expirationjLabel1.setText(DateFormat.getInstance().format(inventory.getDateExpired()));
    
    if(inventory.getWarehouse()!=null){
    warehousejLabel2.setText(inventory.getWarehouse().getOrgName());
    }else{
        warehousejLabel2.setText("not assigned");
    }
    
    invoiceDateLabel1.setText(DateFormat.getInstance().format(invoice.getCreationDate()));
    payableTojLabel1.setText(invoice.getOwedTo().getOrgName() + " " + invoice.getOwedTo().getClass().getSimpleName());
    invoiceByjLabel1.setText(WR.getCreator().getUserName());
    totalOwedjLabel1.setText("$" + Double.toString(invoice.getAmount()));

    paymentOwedjLabel1.setText(WR.getInvoice().getPayment());


    refreshInventory();

}//GEN-LAST:event_managejTableMouseClicked

private void inventoryjTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryjTableMouseClicked
// TODO add your handling code here:
    //make sure ua is empty, or it will give a null pointer.
}//GEN-LAST:event_inventoryjTableMouseClicked

private void treasuryjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treasuryjButtonActionPerformed
// TODO add your handling code here:
    int selectedRow = managejTable.getSelectedRow();
    if (selectedRow < 0 || selectedRow > managejTable.getRowCount()) {
        return;
    }

    WR = (WorkRequest) managejTable.getValueAt(selectedRow, 6);

    WR.getInvoice().setPayment("marked for payment");

    refresh();
    JOptionPane.showMessageDialog(null, "invoice sent to treasury for payment");


}//GEN-LAST:event_treasuryjButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateMadejLabel;
    private javax.swing.JLabel dateMadejLabel1;
    private javax.swing.JLabel diseasejLabel;
    private javax.swing.JLabel diseasejLabel1;
    private javax.swing.JLabel expirationjLabel;
    private javax.swing.JLabel expirationjLabel1;
    private javax.swing.JTable inventoryjTable;
    private javax.swing.JLabel invoiceByjLabel;
    private javax.swing.JLabel invoiceByjLabel1;
    private javax.swing.JLabel invoiceDateLabel;
    private javax.swing.JLabel invoiceDateLabel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTable managejTable;
    private javax.swing.JLabel manufacturerjLabel;
    private javax.swing.JLabel manufacturerjLabel1;
    private javax.swing.JLabel orderedjLabel;
    private javax.swing.JLabel orderedjLabel1;
    private javax.swing.JLabel payableTojLabel;
    private javax.swing.JLabel payableTojLabel1;
    private javax.swing.JLabel paymentOwedjLabel;
    private javax.swing.JLabel paymentOwedjLabel1;
    private javax.swing.JLabel percentjLabel;
    private javax.swing.JLabel percentjLabel1;
    private javax.swing.JLabel priceLabel1;
    private javax.swing.JLabel pricejLabel;
    private javax.swing.JButton refreshjButton;
    private javax.swing.JLabel totalOwedjLabel;
    private javax.swing.JLabel totalOwedjLabel1;
    private javax.swing.JButton treasuryjButton;
    private javax.swing.JLabel vaccinejLabel;
    private javax.swing.JLabel vaccinejLabel1;
    private javax.swing.JLabel warehousejLabel;
    private javax.swing.JLabel warehousejLabel2;
    // End of variables declaration//GEN-END:variables
}
